/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DangKyTaiKhoan;

import DangNhapTaiKhoan.FrmDangNhap;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Huỳnh Cường
 */

public class FrmDangKyTaiKhoan extends javax.swing.JFrame {

    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy"); // Dùng để sửa thứ tự dd/MM/yyyy
    
    UsersDAO usersDAO = new UsersDAO();
    
    public FrmDangKyTaiKhoan() {
        initComponents();
        setLocationRelativeTo(null); // Đưa form ra giữa màn hình khi run 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDangKyTaiKhoan = new javax.swing.JLabel();
        lbTaiKhoanDangKy = new javax.swing.JLabel();
        lbMatKhauDangKy = new javax.swing.JLabel();
        lbNhapLaiMatKhau = new javax.swing.JLabel();
        lbHoTenNguoiDung = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        lbSoDienThoai = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbHinhDangKyTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoanDangKy = new javax.swing.JTextField();
        txtMatKhauDangKy = new javax.swing.JPasswordField();
        txtNhapLaiMatKhau = new javax.swing.JPasswordField();
        txtHoTenNguoiDung = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnDangKyTaiKhoan = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnDangNhapTaiKhoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG KÝ TÀI KHOẢN");
        setResizable(false);

        lbDangKyTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDangKyTaiKhoan.setForeground(new java.awt.Color(255, 0, 0));
        lbDangKyTaiKhoan.setText("ĐĂNG KÝ TÀI KHOẢN");

        lbTaiKhoanDangKy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbTaiKhoanDangKy.setText("Tài khoản: ");

        lbMatKhauDangKy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbMatKhauDangKy.setText("Mật khẩu:");

        lbNhapLaiMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbNhapLaiMatKhau.setText("Nhập lại mật khẩu:");

        lbHoTenNguoiDung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbHoTenNguoiDung.setText("Họ tên:");

        lbNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbNgaySinh.setText("Ngày sinh:");

        lbDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbDiaChi.setText("Địa chỉ:");

        lbSoDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbSoDienThoai.setText("SĐT:");

        lbEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbEmail.setText("Email:");

        lbHinhDangKyTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbHinhDangKyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hinh/iconDangKyTaiKhoan.png"))); // NOI18N

        txtTaiKhoanDangKy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTaiKhoanDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanDangKyActionPerformed(evt);
            }
        });

        txtMatKhauDangKy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNhapLaiMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtHoTenNguoiDung.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnDangKyTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDangKyTaiKhoan.setText("Đăng ký");
        btnDangKyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyTaiKhoanActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnDangNhapTaiKhoan.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnDangNhapTaiKhoan.setText("Đăng nhập tài khoản");
        btnDangNhapTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbHinhDangKyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTaiKhoanDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaiKhoanDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbMatKhauDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbNhapLaiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMatKhauDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDangKyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbHoTenNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(46, 46, 46))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(84, 84, 84)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHoTenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(btnDangNhapTaiKhoan)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lbDangKyTaiKhoan)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbDangKyTaiKhoan)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTaiKhoanDangKy)
                            .addComponent(txtTaiKhoanDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbHinhDangKyTaiKhoan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatKhauDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMatKhauDangKy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNhapLaiMatKhau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoTenNguoiDung)
                            .addComponent(txtHoTenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNgaySinh)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDiaChi)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSoDienThoai)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKyTaiKhoan)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(btnDangNhapTaiKhoan)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Hàm thoát
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        dispose();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    // Chuyển form đăng nhập tài khoản
    private void btnDangNhapTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapTaiKhoanActionPerformed
        new FrmDangNhap().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangNhapTaiKhoanActionPerformed

    // Hàm bool kiểm tra đúng, sai. Nhập đầy đủ thông tin mới cho thêm tài khoản mới
    public boolean checkValidateForm(){
        if (txtTaiKhoanDangKy.getText().isEmpty()||
            txtMatKhauDangKy.getText().isEmpty()||
            txtNhapLaiMatKhau.getText().isEmpty()||
            txtHoTenNguoiDung.getText().isEmpty()||
            txtNgaySinh.getText().isEmpty()||
            txtDiaChi.getText().isEmpty()||       
            txtSDT.getText().length()<10||
            txtEmail.getText().isEmpty())                
        {
           // JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ 10 sdt");
            return false;
        }
        else  
        {
            if (txtSDT.getText().length()>10)
            {
            // JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ 10 sdt");
             return false;
            }
            else {
                return true; 
            }                 
        }     
    }
      
    // Hàm bool kiểm tra đúng, sai. Nhập lại mật khẩu phải trùng với mật khẩu đã nhập
    public boolean checkNhapLaiMatKhau(){
        if (txtMatKhauDangKy.getText().equals(txtNhapLaiMatKhau.getText()))       
        {    
            return true;
        }
        else  
        {       
         // JOptionPane.showMessageDialog(this, "Nhập lại mật khẩu phải trùng với mật khẩu đã nhập!");
            return false;       
        }    
    }
       
    // Lấy dữ liệu đã nhập get vào Table_Users
    public ClassUsers getModel() throws ParseException{
        ClassUsers users = new ClassUsers();
        users.setTaiKhoan(txtTaiKhoanDangKy.getText());
        users.setMatKhau(txtMatKhauDangKy.getText());
        users.setHoTen(txtHoTenNguoiDung.getText());
        users.setNgaySinh(date_format.parse(txtNgaySinh.getText()));
        users.setDiaChi(txtDiaChi.getText());
        users.setSoDienThoai(txtSDT.getText());
        users.setEmail(txtEmail.getText());
               
        return users;
    }
    
    // Hàm đăng ký tài khoản mới
    private void btnDangKyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyTaiKhoanActionPerformed
        if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin hoặc sđt chưa đủ 10 số!"); //Thanh thông báo hiện lên
       }
       else
        {
           if (!checkNhapLaiMatKhau())
           {
              JOptionPane.showMessageDialog(this, "Nhập lại mật khẩu phải trùng với mật khẩu đã nhập!"); //Thanh thông báo hiện lên
           }
           else 
            {
                try {
                ClassUsers users = getModel();
              //System.out.println("=>"+bs.toString());
                if (usersDAO.add(users)>0) {
                   JOptionPane.showMessageDialog(this, "Đăng ký tài khoản mới thành công!","Thông báo",1); //Thanh thông báo hiện lên
                // fillDataTable();
                }
                else{
                   JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại, vui lòng chọn tài khoản khác!","Thông báo",1); 
                }
                    } catch (ParseException ex) {
                        System.out.println("Error:"+ex.toString());
                    }
            }
        }               
    }//GEN-LAST:event_btnDangKyTaiKhoanActionPerformed

    private void txtTaiKhoanDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanDangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangKyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKyTaiKhoan;
    private javax.swing.JButton btnDangNhapTaiKhoan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel lbDangKyTaiKhoan;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHinhDangKyTaiKhoan;
    private javax.swing.JLabel lbHoTenNguoiDung;
    private javax.swing.JLabel lbMatKhauDangKy;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbNhapLaiMatKhau;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTaiKhoanDangKy;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTenNguoiDung;
    private javax.swing.JPasswordField txtMatKhauDangKy;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JPasswordField txtNhapLaiMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTaiKhoanDangKy;
    // End of variables declaration//GEN-END:variables
}
