/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoaiThuoc;


import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author Huỳnh Cường
 */

public class FrmLoaiThuoc extends javax.swing.JFrame {
    
    LoaiThuocDAO ltDAO = new LoaiThuocDAO(); // Lấy dữ liệu từ class LoaiThuocDAO.java
    
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy"); // Dùng để sửa thứ tự dd/MM/yyyy
    
    DefaultTableModel tbModel = new DefaultTableModel(); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một Vectors 
    
    int idThuoc = -1;
   
    public FrmLoaiThuoc() {
        initComponents();   
        setLocationRelativeTo(null); // Đưa form ra giữa màn hình khi run 
        fillDataTable();
        LoadDataToArrayList();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDSLoaiThuoc = new javax.swing.JLabel();
        lbMaThuoc = new javax.swing.JLabel();
        lbTenThuoc = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        txtMaThuoc = new javax.swing.JTextField();
        txtTenThuoc = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnTimKiemTheoMaThuoc = new javax.swing.JButton();
        btnResetForm = new javax.swing.JButton();
        btnXuatFileExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDSLoaiThuoc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DANH SÁCH LOẠI THUỐC");
        setResizable(false);

        lbDSLoaiThuoc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSLoaiThuoc.setForeground(new java.awt.Color(255, 0, 0));
        lbDSLoaiThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSLoaiThuoc.setText("DANH SÁCH LOẠI THUỐC");

        lbMaThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbMaThuoc.setText("Mã thuốc:");

        lbTenThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbTenThuoc.setText("Tên thuốc:");

        lbStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbStatus.setText("Status:");

        txtMaThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaThuocActionPerformed(evt);
            }
        });

        txtTenThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenThuocActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTimKiemTheoMaThuoc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemTheoMaThuoc.setText("Tìm kiếm theo mã thuốc");
        btnTimKiemTheoMaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTheoMaThuocActionPerformed(evt);
            }
        });

        btnResetForm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResetForm.setText("Làm mới");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });

        btnXuatFileExcel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXuatFileExcel.setText("Xuất file excel ");
        btnXuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileExcelActionPerformed(evt);
            }
        });

        TbDSLoaiThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TbDSLoaiThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã thuốc", "Tên thuốc"
            }
        ));
        TbDSLoaiThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbDSLoaiThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbDSLoaiThuoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lbDSLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTenThuoc)
                                    .addComponent(lbMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbStatus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(54, 54, 54)
                                        .addComponent(btnSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnThoat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnTimKiemTheoMaThuoc)
                                            .addComponent(btnResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDSLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMaThuoc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiemTheoMaThuoc)
                        .addComponent(btnXuatFileExcel)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetForm)
                    .addComponent(lbTenThuoc))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Hàm lấy dữ liệu từ SQL đưa vào bảng TbDSLoaiThuoc
    public void fillDataTable(){ 
        DefaultTableModel tbModel = (DefaultTableModel) TbDSLoaiThuoc.getModel();
        tbModel.setRowCount(0); // Xoá data trong table
        for (ClassLoaiThuoc lt : ltDAO.getAllLoaiThuoc()){
            Object dataRow[] = new Object[2];
            dataRow[0] = lt.getMaThuoc();
            dataRow[1] = lt.getTenThuoc();
   
            tbModel.addRow(dataRow);
        }                       
    }
   
    // Hàm bool kiểm tra đúng, sai. Nhập đầy đủ thông tin mới cho thêm loại thuốc mới
    public boolean checkValidateForm(){
        if (txtMaThuoc.getText().isEmpty()||
            txtTenThuoc.getText().isEmpty())
       
        {
           // JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin!");
            return false;
        }
        else  
        {
            return true;                
        }     
    }
    
    // Lấy dữ liệu đã nhập get vào TbDSLoaiThuoc
    public ClassLoaiThuoc getModel() throws ParseException{
        ClassLoaiThuoc lt = new ClassLoaiThuoc();
        lt.setMaThuoc(Integer.parseInt(txtMaThuoc.getText().trim()));
        lt.setTenThuoc(txtTenThuoc.getText().trim());
         
        return lt;
    }
    
    // Đổ dữ liệu lên form, dùng cho envent Mouse Click và tìm kiếm 
    public void setModel (ClassLoaiThuoc lt){
        txtMaThuoc.setText(String.valueOf(lt.getMaThuoc()));
        txtTenThuoc.setText(lt.getTenThuoc());
              
    }
    
    // Hàm thêm 1 loại thuốc mới
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin!"); //Thanh thông báo hiện lên
           lbStatus.setText("Bạn chưa nhập đầy đủ thông tin!"); //Thông báo qua dòng labelStatus
           lbStatus.setForeground(Color.red);
       }
       else{
           try {
               ClassLoaiThuoc lt = getModel();
              // System.out.println("=>"+pk.toString());
               if (ltDAO.add(lt)>0) {
                   JOptionPane.showMessageDialog(this, "Thêm loại thuốc mới thành công!"); //Thanh thông báo hiện lên
                   lbStatus.setText("Thêm loại thuốc mới thành công!"); //Thông báo qua dòng labelStatus
                   lbStatus.setForeground(Color.blue);
                   fillDataTable();
                   LoadDataToArrayList(); 
               }
               else{
                   JOptionPane.showMessageDialog(this, "Thêm loại thuốc mới thất bại!"); 
                   lbStatus.setText("Thêm loại thuốc mới thất bại!");
                   lbStatus.setForeground(Color.red);
               }
           } catch (ParseException ex) {
               System.out.println("Error:"+ex.toString());
           }      
       }               
    }//GEN-LAST:event_btnThemActionPerformed

    //Hàm sửa
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin!");
           lbStatus.setText("Bạn chưa nhập đầy đủ thông tin!");
           lbStatus.setForeground(Color.red);
       }
       else {
        try{
            ClassLoaiThuoc lt = getModel();
            if (ltDAO.update(lt)>0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin loại thuốc thành công!");
                lbStatus.setText("Sửa thông tin loại thuốc thành công!");
                lbStatus.setForeground(Color.blue);
                fillDataTable();
                LoadDataToArrayList(); 
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thông tin loại thuốc thất bại!");
                lbStatus.setText("Sửa thông tin loại thuốc thất bại!");
                lbStatus.setForeground(Color.red);
            }        
        } catch (Exception ex){
            System.out.println (ex.toString());
        }     
    }
       
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaThuocActionPerformed

    private void txtTenThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenThuocActionPerformed

    // Hàm xoá
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    if (ltDAO.delete(idThuoc)>0){
        JOptionPane.showMessageDialog(this, "Xoá thông tin loại thuốc thành công!");
        lbStatus.setText("Xoá thông tin loại thuốc thành công!"); //Thông báo qua dòng labelStatus
        lbStatus.setForeground(Color.blue);
        fillDataTable();
        LoadDataToArrayList(); 
    }
    else{
        JOptionPane.showMessageDialog(this, "Xoá thông tin loại thuốc thất bại!");
        lbStatus.setText("Xoá thông tin loại thuốc thất bại!"); //Thông báo qua dòng labelStatus
        lbStatus.setForeground(Color.red);
    }   
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
     if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    dispose();
            }                    
    }//GEN-LAST:event_btnThoatActionPerformed
  
    // Hàm tìm kiếm theo mã thuốc
    private void btnTimKiemTheoMaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTheoMaThuocActionPerformed
        if (txtMaThuoc.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã thuốc!");
       }
    else {
        try{
            ClassLoaiThuoc findlt = ltDAO.findLoaiThuocByID(Integer.parseInt(txtMaThuoc.getText().trim()));
            
            if (findlt != null){
                JOptionPane.showMessageDialog(this, "Đã tìm thấy mã thuốc: "+txtMaThuoc.getText());
                lbStatus.setText("Đã tìm thấy mã thuốc: "+txtMaThuoc.getText());
                lbStatus.setForeground(Color.blue);
                setModel(findlt); // Tìm thấy mã thuốc sẽ đổ dữ liệu lên form
            }
            else {
                 JOptionPane.showMessageDialog(this, "Không tìm thấy mã thuốc: "+txtMaThuoc.getText());
                 lbStatus.setText("Không tìm thấy mã thuốc: "+txtMaThuoc.getText());
                 lbStatus.setForeground(Color.red);
            }
        } catch (Exception ex){
             System.out.println (ex.toString());
        }     
    }                 
    }//GEN-LAST:event_btnTimKiemTheoMaThuocActionPerformed

    //Hàm reset lại form
    public void resetForm(){
        txtMaThuoc.setText("");
        txtTenThuoc.setText("");
        
        txtMaThuoc.setEnabled(true);
    }
    //
    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetFormActionPerformed
    
    // Hàm LoadDataToArrayList
    ArrayList<ClassLoaiThuoc> arr = new ArrayList<ClassLoaiThuoc>();
    public void LoadDataToArrayList()
    {
        arr.clear();
        try{
            String user="sa";
            String pass="123456";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=DoAnJavaQLPhongKhamTuNhan";
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Table_LoaiThuoc";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){ 
                int maThuoc = rs.getInt("MaThuoc");
                String tenThuoc = rs.getString("TenThuoc");
               
                ClassLoaiThuoc loaithuoc = new ClassLoaiThuoc(maThuoc, tenThuoc);
                arr.add(loaithuoc);
            }
            con.close();
        } 
        catch(Exception ex){
            System.out.println (ex.toString());
        }
    }
    
    // Hàm xuất file excel
    private void btnXuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileExcelActionPerformed
        try{
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("DanhSachLoaiThuoc");
            XSSFRow row = null;
            XSSFCell cell = null;
            row = sheet.createRow(5); // Tạo ra 5 dòng trống đầu tiên trong excel
            cell = row.createCell(0,CellType.STRING);
            cell.setCellValue("STT");
            
            cell = row.createCell(1,CellType.STRING);
            cell.setCellValue("Mã thuốc");
            
            cell = row.createCell(2,CellType.STRING);
            cell.setCellValue("Tên thuốc");
            
            
            for (int i = 0; i<arr.size(); i++)
            {
                ClassLoaiThuoc loaithuoc = arr.get(i);
                row = sheet.createRow(6+i);
                
                cell = row.createCell(0,CellType.NUMERIC);
                cell.setCellValue(i+1);
                
                cell = row.createCell(1,CellType.STRING);
                cell.setCellValue(arr.get(i).getMaThuoc());
                
                cell = row.createCell(2,CellType.STRING);
                cell.setCellValue(arr.get(i).getTenThuoc());
    
            }
            
            File f = new File ("C://Users//Huynh Cuong//Desktop//DanhSachLoaiThuoc.xlsx");
            try{
                FileOutputStream fis = new FileOutputStream(f);
                workbook.write(fis);
                fis.close();
            } catch (FileNotFoundException ex){
                System.out.println (ex.toString());
            }
            catch (IOException ex){
                System.out.println (ex.toString());
            }
            
            JOptionPane.showMessageDialog(this, "Xuất file excel thành công!");
            lbStatus.setText("Xuất file excel thành công!");
            lbStatus.setForeground(Color.blue);
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Xuất file excel thất bại!");
            lbStatus.setText("Xuất file excel thất bại!");
            lbStatus.setForeground(Color.red);
            System.out.println (ex.toString());
        }
    }//GEN-LAST:event_btnXuatFileExcelActionPerformed
 
    // Sử dụng event Mouse Click, khi click vào TbDSLoaiThuoc sẽ đổ dữ liệu lên form
    private void TbDSLoaiThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbDSLoaiThuocMouseClicked
        //   if (evt.getClickCount()==2) // Double click
        //  {
            txtMaThuoc.setEnabled(false); // Mục Mã thuốc bị ẩn để không được sửa khoá chính
            int position = TbDSLoaiThuoc.rowAtPoint(evt.getPoint()); //Vị trí đang chọn
            idThuoc = Integer.parseInt(TbDSLoaiThuoc.getValueAt(position, 0).toString());
            ClassLoaiThuoc loaithuoc = ltDAO.findLoaiThuocByID(idThuoc);
            if (loaithuoc !=null){
                setModel(loaithuoc);
            }
            else{

            }
            //      }
    }//GEN-LAST:event_TbDSLoaiThuocMouseClicked

    //
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoaiThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoaiThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoaiThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoaiThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoaiThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbDSLoaiThuoc;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiemTheoMaThuoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFileExcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDSLoaiThuoc;
    private javax.swing.JLabel lbMaThuoc;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTenThuoc;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextField txtTenThuoc;
    // End of variables declaration//GEN-END:variables
}
