/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BacSi;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author Huỳnh Cường
 */
public class FrmBacSi extends javax.swing.JFrame {
    
    BacSiDAO daoBS = new BacSiDAO(); // Lấy dữ liệu từ class BacSiDAO.java
    
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy"); // Dùng để sửa thứ tự dd/MM/yyyy
    
    DefaultTableModel tbModel = new DefaultTableModel(); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một Vectors 
    
    int idBacSi = -1;
   
    public FrmBacSi() {
        initComponents();   
        setLocationRelativeTo(null); // Đưa form ra giữa màn hình khi run 
        fillDataTable();
        LoadDataToArrayList();     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDSBacSi = new javax.swing.JLabel();
        lbMaBS = new javax.swing.JLabel();
        lbHoTenBS = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        txtMaBS = new javax.swing.JTextField();
        txtHoTenBS = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDSBacSi = new javax.swing.JTable();
        btnTimKiemTheoMaBS = new javax.swing.JButton();
        btnResetForm = new javax.swing.JButton();
        btnXuatFileExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DANH SÁCH BÁC SĨ");
        setResizable(false);

        lbDSBacSi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSBacSi.setForeground(new java.awt.Color(255, 0, 0));
        lbDSBacSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSBacSi.setText("DANH SÁCH BÁC SĨ");

        lbMaBS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbMaBS.setText("Mã BS:");

        lbHoTenBS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbHoTenBS.setText("Họ tên BS:");

        lbNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbNgaySinh.setText("Ngày sinh:");

        lbDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbDiaChi.setText("Địa chỉ:");

        lbSDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbSDT.setText("SĐT:");

        lbGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbGioiTinh.setText("Giới tính:");

        lbStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbStatus.setText("Status:");

        txtMaBS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBSActionPerformed(evt);
            }
        });

        txtHoTenBS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHoTenBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenBSActionPerformed(evt);
            }
        });

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cbbGioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioiTinhActionPerformed(evt);
            }
        });

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        TbDSBacSi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TbDSBacSi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã BS", "Họ tên BS", "Ngày sinh", "Giới tính", "Địa chỉ", "SĐT"
            }
        ));
        TbDSBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbDSBacSiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbDSBacSi);

        btnTimKiemTheoMaBS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemTheoMaBS.setText("Tìm kiếm theo mã BS");
        btnTimKiemTheoMaBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTheoMaBSActionPerformed(evt);
            }
        });

        btnResetForm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResetForm.setText("Làm mới");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });

        btnXuatFileExcel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXuatFileExcel.setText("Xuất file excel ");
        btnXuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbHoTenBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMaBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHoTenBS, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbStatus)
                                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaBS, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnThem))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbGioiTinh)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(btnSua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnXoa)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnResetForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnTimKiemTheoMaBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnThoat))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnXuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lbDSBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDSBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaBS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbGioiTinh)
                        .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiemTheoMaBS)
                        .addComponent(lbMaBS)
                        .addComponent(btnXuatFileExcel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResetForm)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHoTenBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbHoTenBS)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNgaySinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Hàm lấy dữ liệu từ SQL đưa vào bảng bác sĩ 
    public void fillDataTable(){ 
        DefaultTableModel tbModel = (DefaultTableModel) TbDSBacSi.getModel();
        tbModel.setRowCount(0); // Xoá data trong table
        for (ClassBacSi bs : daoBS.getAllBacSi()){
            Object dataRow[] = new Object[6];
            dataRow[0] = bs.getMaBS();
            dataRow[1] = bs.getHoTenBS();
            dataRow[2] = date_format.format(bs.getNgaySinh()); // Sửa lại thứ tự dd/mm/yyyy 
            dataRow[3] = bs.getGioiTinh();
            dataRow[4] = bs.getDiaChi();
            dataRow[5] = bs.getSoDienThoai();
           
            tbModel.addRow(dataRow);
        }                       
    }
   
    // Hàm bool kiểm tra đúng, sai. Nhập đầy đủ thông tin mới cho thêm bác sĩ mới
    public boolean checkValidateForm(){
        if (txtMaBS.getText().isEmpty()||
            txtHoTenBS.getText().isEmpty()||
            txtNgaySinh.getText().isEmpty()||
            cbbGioiTinh.getSelectedItem().toString().isEmpty()||
            txtDiaChi.getText().isEmpty()||
            txtSDT.getText().length()<10)      
            
        {
           // JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ 10 sdt");
            return false;
        }
        else  
        {
            if (txtSDT.getText().length()>10)
            {
            // JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ 10 sdt");
             return false;
            }
            else {
                return true; 
            }                    
        }     
    }
    
    // Lấy dữ liệu đã nhập get vào TbBacSi
    public ClassBacSi getModel() throws ParseException{
        ClassBacSi bs = new ClassBacSi();
        bs.setMaBS(Integer.parseInt(txtMaBS.getText().trim()));
        bs.setHoTenBS(txtHoTenBS.getText().trim());
        bs.setNgaySinh(date_format.parse(txtNgaySinh.getText()));
        bs.setGioiTinh(cbbGioiTinh.getSelectedItem().toString());
        bs.setDiaChi(txtDiaChi.getText().trim());
        bs.setSoDienThoai(txtSDT.getText().trim());
            
        return bs;
    }
    
    // Đổ dữ liệu lên form, dùng cho envent Mouse Click và tìm kiếm 
    public void setModel (ClassBacSi bs){
        txtMaBS.setText(String.valueOf(bs.getMaBS()));
        txtHoTenBS.setText(bs.getHoTenBS());
        txtNgaySinh.setText(date_format.format(bs.getNgaySinh()));
        cbbGioiTinh.setSelectedItem(bs.getGioiTinh());
        txtDiaChi.setText(bs.getDiaChi());
        txtSDT.setText(bs.getSoDienThoai());
              
    }
    
    // Hàm thêm 1 bác sĩ mới
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin hoặc sđt chưa đủ 10 số, không khoảng cách sđt!"); //Thanh thông báo hiện lên
           lbStatus.setText("Bạn chưa nhập đầy đủ thông tin hoặc sđt chưa đủ 10 số, không khoảng cách sđt!"); //Thông báo qua dòng labelStatus
           lbStatus.setForeground(Color.red);
       }
       else{
           try {
               ClassBacSi bs = getModel();
             //  System.out.println("=>"+bs.toString());
               if (daoBS.add(bs)>0) {
                   JOptionPane.showMessageDialog(this, "Thêm bác sĩ mới thành công!"); //Thanh thông báo hiện lên
                   lbStatus.setText("Thêm bác sĩ mới thành công!"); //Thông báo qua dòng labelStatus
                   lbStatus.setForeground(Color.blue);
                   fillDataTable();
                   LoadDataToArrayList(); 
               }
               else{
                   JOptionPane.showMessageDialog(this, "Thêm bác sĩ mới thất bại!"); 
                   lbStatus.setText("Thêm bác sĩ mới thất bại!");
                   lbStatus.setForeground(Color.red);
               }
           } catch (ParseException ex) {
               System.out.println("Error:"+ex.toString());
           }      
       }               
    }//GEN-LAST:event_btnThemActionPerformed

    //Hàm sửa
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin hoặc sđt chưa đủ 10 số!");
           lbStatus.setText("Bạn chưa nhập đầy đủ thông tin hoặc sđt chưa đủ 10 số!");
           lbStatus.setForeground(Color.red);
       }
       else {
        try{
            ClassBacSi bs = getModel();
            if (daoBS.update(bs)>0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin bác sĩ thành công!");
                lbStatus.setText("Sửa thông tin bác sĩ thành công!");
                lbStatus.setForeground(Color.blue);
                fillDataTable();
                LoadDataToArrayList(); 
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thông tin bác sĩ thất bại!");
                lbStatus.setText("Sửa thông tin bác sĩ thất bại!");
                lbStatus.setForeground(Color.red);
            }        
        } catch (Exception ex){
            System.out.println (ex.toString());
        }     
    }
       
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBSActionPerformed

    private void txtHoTenBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenBSActionPerformed

    private void cbbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGioiTinhActionPerformed

    // Hàm xoá
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    if (daoBS.delete(idBacSi)>0){
        JOptionPane.showMessageDialog(this, "Xoá thông tin bác sĩ thành công!");
        lbStatus.setText("Xoá thông tin bác sĩ thành công!"); //Thông báo qua dòng labelStatus
        lbStatus.setForeground(Color.blue);
        fillDataTable();
        LoadDataToArrayList(); 
    }
    else{
        JOptionPane.showMessageDialog(this, "Xoá thông tin bác sĩ thất bại!");
        lbStatus.setText("Xoá thông tin bác sĩ thất bại!"); //Thông báo qua dòng labelStatus
        lbStatus.setForeground(Color.red);
    }   
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
     if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    dispose();
            }                    
    }//GEN-LAST:event_btnThoatActionPerformed
  
    // Hàm tìm kiếm theo mã bác sĩ
    private void btnTimKiemTheoMaBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTheoMaBSActionPerformed
        if (txtMaBS.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã bác sĩ!");
       }
    else {
        try{
            ClassBacSi findbs = daoBS.findBacSiByID(Integer.parseInt(txtMaBS.getText().trim()));
            
            if (findbs != null){
                JOptionPane.showMessageDialog(this, "Đã tìm thấy mã BS: "+txtMaBS.getText());
                lbStatus.setText("Đã tìm thấy mã bác sĩ: "+txtMaBS.getText());
                lbStatus.setForeground(Color.blue);
                setModel(findbs); // Tìm thấy mã bác sĩ sẽ đổ dữ liệu lên form
            }
            else {
                 JOptionPane.showMessageDialog(this, "Không tìm thấy mã BS: "+txtMaBS.getText());
                 lbStatus.setText("Không tìm thấy mã bác sĩ: "+txtMaBS.getText());
                 lbStatus.setForeground(Color.red);
            }
        } catch (Exception ex){
             System.out.println (ex.toString());
        }     
    }                 
    }//GEN-LAST:event_btnTimKiemTheoMaBSActionPerformed

    //Hàm reset lại form
    public void resetForm(){
        txtMaBS.setText("");
        txtHoTenBS.setText("");
        txtNgaySinh.setText("");
        cbbGioiTinh.setSelectedIndex(0);
        txtDiaChi.setText("");
        txtSDT.setText("");
        
        txtMaBS.setEnabled(true);
        txtSDT.setEnabled(true);
    }
    //
    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetFormActionPerformed
    
    // Hàm LoadDataToArrayList
    ArrayList<ClassBacSi> arr = new ArrayList<ClassBacSi>();
    public void LoadDataToArrayList()
    {
        arr.clear();
        try{
            String user="sa";
            String pass="123456";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=DoAnJavaQLPhongKhamTuNhan";
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Table_BacSi";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){ 
                int maBS = rs.getInt("MaBS");
                String hotenBS = rs.getString("HoTenBS");
                Date ngaysinh = rs.getDate("NgaySinh"); 
                String gioitinh = rs.getString("GioiTinh");
                String diachi = rs.getString("DiaChi");
                String sdt = rs.getString("SoDienThoai");
               
                ClassBacSi bacsi = new ClassBacSi(maBS, hotenBS, ngaysinh, gioitinh, diachi, sdt);
                arr.add(bacsi);
            }
            con.close();
        } 
        catch(Exception ex){
            System.out.println (ex.toString());
        }
    }
    
    // Hàm xuất file excel
    private void btnXuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileExcelActionPerformed
        try{
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("DanhSachBacSi");
            XSSFRow row = null;
            XSSFCell cell = null;
            row = sheet.createRow(5); // Tạo ra 5 dòng trống đầu tiên trong excel
            cell = row.createCell(0,CellType.STRING);
            cell.setCellValue("STT");
            
            cell = row.createCell(1,CellType.STRING);
            cell.setCellValue("Mã BS");
            
            cell = row.createCell(2,CellType.STRING);
            cell.setCellValue("Họ tên BS");
            
            cell = row.createCell(3,CellType.STRING);
            cell.setCellValue("Ngày sinh");
            
            cell = row.createCell(4,CellType.STRING);
            cell.setCellValue("Giới tính");
           
            cell = row.createCell(5,CellType.STRING);
            cell.setCellValue("Địa chỉ");
            
            cell = row.createCell(6,CellType.STRING);
            cell.setCellValue("SĐT");
            
            for (int i = 0; i<arr.size(); i++)
            {
                ClassBacSi bacsi = arr.get(i);
                row = sheet.createRow(6+i);
                
                cell = row.createCell(0,CellType.NUMERIC);
                cell.setCellValue(i+1);
                
                cell = row.createCell(1,CellType.STRING);
                cell.setCellValue(arr.get(i).getMaBS());
                
                cell = row.createCell(2,CellType.STRING);
                cell.setCellValue(arr.get(i).getHoTenBS());
                
                cell = row.createCell(3,CellType.STRING);
                cell.setCellValue(arr.get(i).getNgaySinh());
                
                cell = row.createCell(4,CellType.STRING);
                cell.setCellValue(arr.get(i).getGioiTinh());
                
                cell = row.createCell(5,CellType.STRING);
                cell.setCellValue(arr.get(i).getDiaChi());
                
                cell = row.createCell(6,CellType.STRING);
                cell.setCellValue(arr.get(i).getSoDienThoai());
    
            }
            
            File f = new File ("C://Users//Huynh Cuong//OneDrive//Máy tính//DanhSachBacSi.xlsx");  
            try{
                FileOutputStream fis = new FileOutputStream(f);
                workbook.write(fis);
                fis.close();
            } catch (FileNotFoundException ex){
                System.out.println (ex.toString());
            }
            catch (IOException ex){
                System.out.println (ex.toString());
            }
            
            JOptionPane.showMessageDialog(this, "Xuất file excel thành công!");
            lbStatus.setText("Xuất file excel thành công!");
            lbStatus.setForeground(Color.blue);
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Xuất file excel thất bại!");
            lbStatus.setText("Xuất file excel thất bại!");
            lbStatus.setForeground(Color.red);
            System.out.println (ex.toString());
        }
    }//GEN-LAST:event_btnXuatFileExcelActionPerformed
 
    // Sử dụng event Mouse Click, khi click vào TbBacSi sẽ đổ dữ liệu lên form
    private void TbDSBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbDSBacSiMouseClicked
        //   if (evt.getClickCount()==2) // Double click
        //  {
            txtMaBS.setEnabled(false); // Mục Mã bác sĩ bị ẩn để không được sửa khoá chính
            int position = TbDSBacSi.rowAtPoint(evt.getPoint()); //Vị trí đang chọn
            idBacSi = Integer.parseInt(TbDSBacSi.getValueAt(position, 0).toString());
            ClassBacSi bacsi = daoBS.findBacSiByID(idBacSi);
            if (bacsi !=null){
                setModel(bacsi);
            }
            else{

            }
            //      }
    }//GEN-LAST:event_TbDSBacSiMouseClicked
    
    //
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBacSi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBacSi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbDSBacSi;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiemTheoMaBS;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFileExcel;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDSBacSi;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTenBS;
    private javax.swing.JLabel lbMaBS;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTenBS;
    private javax.swing.JTextField txtMaBS;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
