/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PhongKham;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author Huỳnh Cường
 */

public class FrmPhongKham extends javax.swing.JFrame {
    
    PhongKhamDAO daoPK = new PhongKhamDAO(); // Lấy dữ liệu từ class PhongKhamDAO.java
    
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy"); // Dùng để sửa thứ tự dd/MM/yyyy
    
    DefaultTableModel tbModel = new DefaultTableModel(); //DefaultTableModel lưu trữ dữ liệu cho JTable trong một Vectors 
    
    int idPhongKham = -1;
   
    public FrmPhongKham() {
        initComponents();   
        setLocationRelativeTo(null); // Đưa form ra giữa màn hình khi run 
        fillDataTable();
        LoadDataToArrayList();     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDSPhongKham = new javax.swing.JLabel();
        lbMaPK = new javax.swing.JLabel();
        lbTenPK = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        txtMaPK = new javax.swing.JTextField();
        txtTenPK = new javax.swing.JTextField();
        btnTimKiemTheoMaPK = new javax.swing.JButton();
        btnResetForm = new javax.swing.JButton();
        btnXuatFileExcel = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDSPhongKham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DANH SÁCH PHÒNG KHÁM");
        setResizable(false);

        lbDSPhongKham.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbDSPhongKham.setForeground(new java.awt.Color(255, 0, 0));
        lbDSPhongKham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSPhongKham.setText("DANH SÁCH PHÒNG KHÁM");

        lbMaPK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbMaPK.setText("Mã PK:");

        lbTenPK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbTenPK.setText("Tên PK:");

        lbStatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbStatus.setText("Status:");

        txtMaPK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPKActionPerformed(evt);
            }
        });

        txtTenPK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPKActionPerformed(evt);
            }
        });

        btnTimKiemTheoMaPK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemTheoMaPK.setText("Tìm kiếm theo mã PK");
        btnTimKiemTheoMaPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTheoMaPKActionPerformed(evt);
            }
        });

        btnResetForm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResetForm.setText("Làm mới");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });

        btnXuatFileExcel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXuatFileExcel.setText("Xuất file excel ");
        btnXuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileExcelActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        TbDSPhongKham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TbDSPhongKham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã PK", "Tên PK"
            }
        ));
        TbDSPhongKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbDSPhongKhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbDSPhongKham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lbDSPhongKham, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTenPK)
                                    .addComponent(lbMaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbStatus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnThem)
                                                .addGap(50, 50, 50)
                                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTimKiemTheoMaPK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnXuatFileExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(btnResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(btnThoat)))))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDSPhongKham, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaPK)
                    .addComponent(txtMaPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemTheoMaPK)
                    .addComponent(btnResetForm))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatFileExcel)
                    .addComponent(lbTenPK))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Hàm lấy dữ liệu từ SQL đưa vào bảng TbDSPhongKham
    public void fillDataTable(){ 
        DefaultTableModel tbModel = (DefaultTableModel) TbDSPhongKham.getModel();
        tbModel.setRowCount(0); // Xoá data trong table
        for (ClassPhongKham pk : daoPK.getAllPhongKham()){
            Object dataRow[] = new Object[2];
            dataRow[0] = pk.getMaPK();
            dataRow[1] = pk.getTenPK();
   
            tbModel.addRow(dataRow);
        }                       
    }
   
    // Hàm bool kiểm tra đúng, sai. Nhập đầy đủ thông tin mới cho thêm phòng khám mới
    public boolean checkValidateForm(){
        if (txtMaPK.getText().isEmpty()||
            txtTenPK.getText().isEmpty())
       
        {
           // JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ 10 sdt");
            return false;
        }
        else  
        {
            return true;                
        }     
    }
    
    // Lấy dữ liệu đã nhập get vào TbPhongKham
    public ClassPhongKham getModel() throws ParseException{
        ClassPhongKham pk = new ClassPhongKham();
        pk.setMaPK(Integer.parseInt(txtMaPK.getText().trim()));
        pk.setTenPK(txtTenPK.getText().trim());
         
        return pk;
    }
    
    // Đổ dữ liệu lên form, dùng cho envent Mouse Click và tìm kiếm 
    public void setModel (ClassPhongKham pk){
        txtMaPK.setText(String.valueOf(pk.getMaPK()));
        txtTenPK.setText(pk.getTenPK());
              
    }
    
    // Hàm thêm 1 phòng khám mới
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin!"); //Thanh thông báo hiện lên
           lbStatus.setText("Bạn chưa nhập đầy đủ thông tin!"); //Thông báo qua dòng labelStatus
           lbStatus.setForeground(Color.red);
       }
       else{
           try {
               ClassPhongKham pk = getModel();
              // System.out.println("=>"+pk.toString());
               if (daoPK.add(pk)>0) {
                   JOptionPane.showMessageDialog(this, "Thêm phòng khám mới thành công!"); //Thanh thông báo hiện lên
                   lbStatus.setText("Thêm phòng khám mới thành công!"); //Thông báo qua dòng labelStatus
                   lbStatus.setForeground(Color.blue);
                   fillDataTable();
                   LoadDataToArrayList(); 
               }
               else{
                   JOptionPane.showMessageDialog(this, "Thêm phòng khám mới thất bại!"); 
                   lbStatus.setText("Thêm phòng khám mới thất bại!");
                   lbStatus.setForeground(Color.red);
               }
           } catch (ParseException ex) {
               System.out.println("Error:"+ex.toString());
           }      
       }               
    }//GEN-LAST:event_btnThemActionPerformed

    //Hàm sửa
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       if (!checkValidateForm())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin!");
           lbStatus.setText("Bạn chưa nhập đầy đủ thông tin!");
           lbStatus.setForeground(Color.red);
       }
       else {
        try{
            ClassPhongKham pk = getModel();
            if (daoPK.update(pk)>0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin phòng khám thành công!");
                lbStatus.setText("Sửa thông tin phòng khám thành công!");
                lbStatus.setForeground(Color.blue);
                fillDataTable();
                LoadDataToArrayList(); 
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thông tin phòng khám thất bại!");
                lbStatus.setText("Sửa thông tin phòng khám thất bại!");
                lbStatus.setForeground(Color.red);
            }        
        } catch (Exception ex){
            System.out.println (ex.toString());
        }     
    }
       
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPKActionPerformed

    private void txtTenPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPKActionPerformed

    // Hàm xoá
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    if (daoPK.delete(idPhongKham)>0){
        JOptionPane.showMessageDialog(this, "Xoá thông tin phòng khám thành công!");
        lbStatus.setText("Xoá thông tin phòng khám thành công!"); //Thông báo qua dòng labelStatus
        lbStatus.setForeground(Color.blue);
        fillDataTable();
        LoadDataToArrayList(); 
    }
    else{
        JOptionPane.showMessageDialog(this, "Xoá thông tin phòng khám thất bại!");
        lbStatus.setText("Xoá thông tin phòng khám thất bại!"); //Thông báo qua dòng labelStatus
        lbStatus.setForeground(Color.red);
    }   
    }//GEN-LAST:event_btnXoaActionPerformed

    // Hàm thoát
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
     if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    dispose();
            }                    
    }//GEN-LAST:event_btnThoatActionPerformed
  
    // Hàm tìm kiếm theo mã phòng khám
    private void btnTimKiemTheoMaPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTheoMaPKActionPerformed
        if (txtMaPK.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã phòng khám!");
       }
    else {
        try{
            ClassPhongKham findpk = daoPK.findPhongKhamByID(Integer.parseInt(txtMaPK.getText().trim()));
            
            if (findpk != null){
                JOptionPane.showMessageDialog(this, "Đã tìm thấy mã PK: "+txtMaPK.getText());
                lbStatus.setText("Đã tìm thấy mã phòng khám: "+txtMaPK.getText());
                lbStatus.setForeground(Color.blue);
                setModel(findpk); // Tìm thấy mã phòng khám sẽ đổ dữ liệu lên form
            }
            else {
                 JOptionPane.showMessageDialog(this, "Không tìm thấy mã PK: "+txtMaPK.getText());
                 lbStatus.setText("Không tìm thấy mã phòng khám: "+txtMaPK.getText());
                 lbStatus.setForeground(Color.red);
            }
        } catch (Exception ex){
             System.out.println (ex.toString());
        }     
    }                 
    }//GEN-LAST:event_btnTimKiemTheoMaPKActionPerformed

    //Hàm reset lại form
    public void resetForm(){
        txtMaPK.setText("");
        txtTenPK.setText("");
        
        txtMaPK.setEnabled(true);
    }
    //
    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetFormActionPerformed
    
    // Hàm LoadDataToArrayList
    ArrayList<ClassPhongKham> arr = new ArrayList<ClassPhongKham>();
    public void LoadDataToArrayList()
    {
        arr.clear();
        try{
            String user="sa";
            String pass="123456";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=DoAnJavaQLPhongKhamTuNhan";
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from Table_PhongKham";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){ 
                int maPK = rs.getInt("MaPK");
                String tenPK = rs.getString("TenPK");
               
                ClassPhongKham phongkham = new ClassPhongKham(maPK, tenPK);
                arr.add(phongkham);
            }
            con.close();
        } 
        catch(Exception ex){
            System.out.println (ex.toString());
        }
    }
    
    // Hàm xuất file excel
    private void btnXuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileExcelActionPerformed
        try{
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("DanhSachPhongKham");
            XSSFRow row = null;
            XSSFCell cell = null;
            row = sheet.createRow(5); // Tạo ra 5 dòng trống đầu tiên trong excel
            cell = row.createCell(0,CellType.STRING);
            cell.setCellValue("STT");
            
            cell = row.createCell(1,CellType.STRING);
            cell.setCellValue("Mã PK");
            
            cell = row.createCell(2,CellType.STRING);
            cell.setCellValue("Tên PK");
            
            
            for (int i = 0; i<arr.size(); i++)
            {
                ClassPhongKham phongkham = arr.get(i);
                row = sheet.createRow(6+i);
                
                cell = row.createCell(0,CellType.NUMERIC);
                cell.setCellValue(i+1);
                
                cell = row.createCell(1,CellType.STRING);
                cell.setCellValue(arr.get(i).getMaPK());
                
                cell = row.createCell(2,CellType.STRING);
                cell.setCellValue(arr.get(i).getTenPK());
    
            }
            
            File f = new File ("C://Users//Huynh Cuong//Desktop//DanhSachPhongKham.xlsx");
            try{
                FileOutputStream fis = new FileOutputStream(f);
                workbook.write(fis);
                fis.close();
            } catch (FileNotFoundException ex){
                System.out.println (ex.toString());
            }
            catch (IOException ex){
                System.out.println (ex.toString());
            }
            
            JOptionPane.showMessageDialog(this, "Xuất file excel thành công!");
            lbStatus.setText("Xuất file excel thành công!");
            lbStatus.setForeground(Color.blue);
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Xuất file excel thất bại!");
            lbStatus.setText("Xuất file excel thất bại!");
            lbStatus.setForeground(Color.red);
            System.out.println (ex.toString());
        }
    }//GEN-LAST:event_btnXuatFileExcelActionPerformed
 
    // Sử dụng event Mouse Click, khi click vào TbPhongKham sẽ đổ dữ liệu lên form
    private void TbDSPhongKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbDSPhongKhamMouseClicked
        //   if (evt.getClickCount()==2) // Double click
        //  {
            txtMaPK.setEnabled(false); // Mục Mã phòng khám bị ẩn để không được sửa khoá chính
            int position = TbDSPhongKham.rowAtPoint(evt.getPoint()); //Vị trí đang chọn
            idPhongKham = Integer.parseInt(TbDSPhongKham.getValueAt(position, 0).toString());
            ClassPhongKham phongkham = daoPK.findPhongKhamByID(idPhongKham);
            if (phongkham !=null){
                setModel(phongkham);
            }
            else{

            }
            //      }
    }//GEN-LAST:event_TbDSPhongKhamMouseClicked

    //
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPhongKham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPhongKham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbDSPhongKham;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiemTheoMaPK;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFileExcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDSPhongKham;
    private javax.swing.JLabel lbMaPK;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTenPK;
    private javax.swing.JTextField txtMaPK;
    private javax.swing.JTextField txtTenPK;
    // End of variables declaration//GEN-END:variables
}
